using System.Collections.Generic; using Microsoft.Win32; namespace RadeonSoftwareSlimmer.Optimize; public static class TweakCatalog { private const string Multimedia=@"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile"; public static IReadOnlyList<SystemTweak> All {get;}=new List<SystemTweak>{new SystemTweak
            {
                Id = "priority-separation",
                Title = "Win32 Separation Control",
                Category = TweakCategory.Performance,
                Summary = "Choose CPU time-slice behavior for foreground apps and background work. Use Adjust to select a scheduling preference.",
                TradeOff = "Changes scheduling quantum preference, not process priority. Less foreground boost can favor background work. Historical options are not Windows 11 performance guarantees. Restart after changing; Restore recovers your saved original state.",
                Grade = TweakGrade.A,
                Source = "Microsoft Windows Internals — quantum settings (historical): https://live.sysinternals.com/files/WindowsInternals-Ch05.pdf",
                ManualOnly = true,
                IndividualApplyOnly = true,
                RebootRequired = true,
                Hive = TweakHive.LocalMachine,
                KeyPath = @"SYSTEM\CurrentControlSet\Control\PriorityControl",
                ValueName = "Win32PrioritySeparation",
                ValueKind = RegistryValueKind.DWord,
                TargetValue = 0x26,
                DefaultValue = 2,
                Presets = new[]
                {
                    new TweakPreset("Programs · 3x foreground · 0x26 / 38", 0x26),
                    new TweakPreset("Short variable · 2x foreground · 0x25 / 37", 0x25),
                    new TweakPreset("Short variable · equal slices · 0x24 / 36", 0x24),
                    new TweakPreset("Background services · long fixed · 0x18 / 24", 0x18),
                    new TweakPreset("Windows edition defaults · boost 2 · 0x02 / 2", 0x02),
                },
            },
new SystemTweak
            {
                ApplyBlockedReason = "MMCSS reservations are not a general gaming-performance control. Rion does not change this value.",
                Id = "system-responsiveness",
                Title = "Lower Multimedia CPU Reservation",
                Category = TweakCategory.Performance,
                Summary = "Changes the MMCSS background CPU reservation from its configured value to 10%. This affects MMCSS scheduling and does not establish a general FPS improvement.",
                TradeOff = "Only registered MMCSS threads use task profiles. Values below 10 become 20; this is not a global foreground CPU allocation.",
                Grade = TweakGrade.A,
                Source = "Microsoft — Multimedia Class Scheduler Service (SystemResponsiveness)",
                Hive = TweakHive.LocalMachine,
                KeyPath = Multimedia,
                ValueName = "SystemResponsiveness",
                ValueKind = RegistryValueKind.DWord,
                TargetValue = 10,
                DefaultValue = 20,
            },
new SystemTweak
            {
                Id = "gamedvr-store-off",
                Title = "Disable Background Game Recording (GameDVR)",
                Category = TweakCategory.Graphics,
                Summary = "Turns off background game recording to free up CPU/GPU.",
                TradeOff = "Game Bar recording may become unavailable. This does not disable third-party capture tools.",
                Grade = TweakGrade.C,
                Source = "GameConfigStore\\GameDVR_Enabled; long-standing gaming tweak",
                Hive = TweakHive.CurrentUser,
                KeyPath = @"System\GameConfigStore",
                ValueName = "GameDVR_Enabled",
                ValueKind = RegistryValueKind.DWord,
                TargetValue = 0,
                DefaultValue = 1,
            },
new SystemTweak
            {
                Id = "gamedvr-policy-off",
                Title = "GameDVR Policy: Fully Disabled",
                Category = TweakCategory.Graphics,
                Summary = "Turns off game recording system-wide.",
                TradeOff = "Disables Windows game recording for all users; keep enabled if capture is needed.",
                Grade = TweakGrade.A,
                Source = "Microsoft — AllowGameDVR policy",
                Hive = TweakHive.LocalMachine,
                KeyPath = @"SOFTWARE\Policies\Microsoft\Windows\GameDVR",
                ValueName = "AllowGameDVR",
                ValueKind = RegistryValueKind.DWord,
                TargetValue = 0,
                DefaultValue = null,
            },
new SystemTweak
            {
                Id = "appcapture-off",
                Title = "Disable App Capture",
                Category = TweakCategory.Graphics,
                Summary = "Stops the background app-capture hook GameDVR uses.",
                TradeOff = "Windows app capture becomes unavailable.",
                Grade = TweakGrade.C,
                Source = "CurrentVersion\\GameDVR\\AppCaptureEnabled",
                Hive = TweakHive.CurrentUser,
                KeyPath = @"SOFTWARE\Microsoft\Windows\CurrentVersion\GameDVR",
                ValueName = "AppCaptureEnabled",
                ValueKind = RegistryValueKind.DWord,
                TargetValue = 0,
                DefaultValue = 1,
            }}; }